#!/bin/bash
# setup-github-remote.sh - Configura el repositorio remoto en GitHub

echo "📦 Configuración de Repositorio Remoto"
echo "====================================="
echo ""
echo "Para crear el repositorio en GitHub:"
echo ""
echo "1. Ve a: https://github.com/new"
echo "2. Nombre sugerido: Avicloud-Autonomous-v2"
echo "3. Descripción: Sistema Autónomo de Desarrollo v2 para Avicloud Display"
echo "4. Tipo: Privado"
echo "5. NO inicialices con README, .gitignore o licencia"
echo ""
echo "Después de crear el repositorio, ejecuta:"
echo ""
echo "git remote add origin https://github.com/ariverosh/Avicloud-Autonomous-v2.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "O si prefieres usar el token PAT existente:"
echo ""
echo "git remote add origin https://ariverosh:TU_TOKEN@github.com/ariverosh/Avicloud-Autonomous-v2.git"
echo ""
echo "Estado actual del repositorio local:"
echo "------------------------------------"
git log --oneline -n 5
echo ""
echo "Archivos en el repositorio: $(git ls-files | wc -l)"